apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-11-27T18:07:33Z"
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 12.0.1
  name: grafana
  namespace: monitoring
  resourceVersion: "60075"
  uid: dee108f8-173f-4aa8-adb0-7406d02b6488
spec:
  clusterIP: 10.233.50.0
  clusterIPs:
  - 10.233.50.0
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: http
    nodePort: 30080
  selector:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-prometheus
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
